words:
  - apiv
  - fdfe
  - gomod
  - gvisor
  - liblaf
  - lipulai
  - nthu
ignorePaths:
  - "*-lock.*"
  - "*.lock"
  - cspell.config.yaml
dictionaries:
  - bash
  - cpp
  - cpp-refined
  - dotnet
  - en-gb
  - makefile
  - npm
  - php
  - typescript
allowCompoundWords: true
